[workspace]
resolver = "2"
members = [
    "voice_nft",
    "voice_token",
    "marketplace",
    "dao",
    "orchestrator"
]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
